version: '3.8'

services:
  app:
    build: .
    container_name: chatsystem_app
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/chatsystem_development
    depends_on:
      - db
    networks:
      - chatsystem_network

  db:
    build: ./containers/postgres
    container_name: chatsystem_db
    environment:
      - POSTGRES_DB=chatsystem_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatsystem_network

  nginx:
    build: ./containers/nginx
    container_name: chatsystem_nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - chatsystem_network

volumes:
  postgres_data:
  bundle_cache:

networks:
  chatsystem_network:
    driver: bridge 